### ISSUE TITLE
2DS updated to 11.9 on its own??

### ISSUE THREAD

**Issue by mrmystik** [marcrobledo/acnl-editor#45] opened 2019-01-09 20:33 UTC
So I'm not sure when 11.9 dropped but I might have missed something about whether or not it updates when turned off. I play new leaf a LOT, so the battery usually gets drained and I have to charge. Then again, I turn off my 2ds after exporting my saves and before taking the sd card out. So I'm just wondering if you would be able to fix this issue to your best ability (if possible) because I have 3 ugly villagers I want to replace, a lack of flowers, you name it. Thanks!!

**Comment by StevenSeegal** [comment] 2019-01-11 13:32
1) I don't know what your 2DS's **Firmware** version has to do with a **Game Save Editor**. This editor only allows you to edit your save file, which you have to extract and import yourself on the 2DS with a backup program like Checkpoint. This Editor, AC:NL and it's save has nothing to do with the Firmware of your console.

2) Your description is also bad, I can't even make out what you want to be fixed, what the issue is, etc.

**Comment by mrmystik** [comment] 2019-01-11 13:46
Oh, I'm sorry. I thought a little more about it and it just might be some problem I'm having with importing the game. I haven't done it in a while since I deleted my old town and took a break for a while. So it's most likely my forgetfulness. Thank you anyways.

**Comment by erithemermaid** [comment] 2019-01-29 15:41
Please close the issue?

**Closed** 2019-01-29 15:51 UTC
